(()=>{
  window.popupConfig=window.popupConfig||{};
  const oldLoadAll=window.loadAll,oldSaveAll=window.saveAll,oldSaveCurrent=window.saveCurrent;
  const defaults={enabled:true,title:'모현소망교회',highlight:'소식 알아보기 !',channelTitle:'< 카카오톡 채널 & 유튜브 >',description:'교회 소식과 말씀 영상을 더 편하게 만나보세요.',slogan:'성령과 진리로 예배드리는 교회',verse:'요한복음 4:24',kakaoTitle:'카카오톡 채널',kakaoDescription:'교회 공지와 행사, 새로운 소식을 가장 빠르게 받아보세요.',kakaoUrl:'https://pf.kakao.com/_BYtgG',kakaoQr:'',youtubeTitle:'YouTube 채널',youtubeDescription:'주일예배 말씀과 교회 영상을 편리하게 확인하세요.',youtubeUrl:'',youtubeQr:'',signature:'함께 걸어가는 믿음의 길, 모현소망교회',closeLabel:'이번 접속에서 닫기'};
  const norm=()=>{window.popupConfig={...defaults,...(window.popupConfig||{})}};
  const nav=document.getElementById('sideNav');
  if(nav&&!nav.querySelector('[data-page="popupEditor"]')){const b=document.createElement('button');b.dataset.page='popupEditor';b.textContent='팝업 편집';const media=nav.querySelector('[data-page="media"]');media?.nextSibling?nav.insertBefore(b,media.nextSibling):nav.appendChild(b);b.onclick=()=>openPopupEditor()}
  const ed=document.getElementById('editor');
  if(ed&&!ed.querySelector('[data-page="popupEditor"]')){const s=document.createElement('section');s.className='page';s.dataset.page='popupEditor';s.innerHTML='<div id="popupEditorRoot"></div>';ed.insertBefore(s,ed.querySelector('.savebar')||null)}
  window.openPopupEditor=function(){currentPage='popupEditor';document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.dataset.page==='popupEditor'));document.querySelectorAll('#sideNav button').forEach(b=>b.classList.toggle('active',b.dataset.page==='popupEditor'));document.getElementById('pageTitle').textContent='팝업 편집';document.getElementById('pageDesc').textContent='홈 화면 팝업의 문구·링크·QR·노출 여부를 관리합니다.';renderPopupEditor();window.scrollTo({top:0,behavior:'smooth'})};
  const row=(label,key,full=false,type='input')=>`<div class="${full?'full':''}"><label>${label}</label>${type==='textarea'?`<textarea oninput="popupConfig['${key}']=this.value;dirty()">${esc(popupConfig[key]||'')}</textarea>`:`<input value="${esc(popupConfig[key]||'')}" oninput="popupConfig['${key}']=this.value;dirty()">`}</div>`;
  const qrRow=(label,key)=>`<div class="full"><label>${label}</label><div class="image-input-row"><input value="${esc(popupConfig[key]||'')}" oninput="popupConfig['${key}']=this.value;dirty()"><button class="ghost" onclick="openMediaPicker('popup:${key}')">이미지 선택</button><button class="ghost" onclick="popupConfig['${key}']='';renderPopupEditor();dirty()">비우기</button></div>${popupConfig[key]?`<div class="slot-preview" style="max-width:180px;aspect-ratio:1;background-size:cover;background-position:center;background-image:url('${esc(popupConfig[key])}?v=${Date.now()}')"></div>`:''}</div>`;
  window.renderPopupEditor=function(){norm();const root=document.getElementById('popupEditorRoot');if(!root)return;root.innerHTML=`<section class="card"><div class="section-head"><div><h2>홈 화면 팝업</h2><p class="muted">카카오톡 채널·YouTube 홍보 팝업을 직접 편집합니다.</p></div><div><button class="ghost" onclick="window.open('/index.html?popup=1&v='+Date.now(),'_blank')">팝업 미리보기</button> <button onclick="savePopupConfig()">팝업 저장</button></div></div><div class="form-grid"><div class="full"><label style="display:flex;align-items:center;gap:10px"><input type="checkbox" style="width:auto" ${popupConfig.enabled?'checked':''} onchange="popupConfig.enabled=this.checked;dirty()"> 팝업 사용</label></div>${row('제목 앞부분','title')}${row('강조 제목','highlight')}${row('채널 안내 제목','channelTitle',true)}${row('소개 문구','description',true,'textarea')}${row('상단 표어','slogan')}${row('성경 구절','verse')}${row('카카오톡 제목','kakaoTitle')}${row('카카오톡 링크','kakaoUrl')}${row('카카오톡 설명','kakaoDescription',true,'textarea')}${qrRow('카카오톡 QR 이미지','kakaoQr')}${row('YouTube 제목','youtubeTitle')}${row('YouTube 링크','youtubeUrl')}${row('YouTube 설명','youtubeDescription',true,'textarea')}${qrRow('YouTube QR 이미지','youtubeQr')}${row('하단 문구','signature',true)}${row('닫기 버튼 문구','closeLabel',true)}</div></section>`};
  window.savePopupConfig=async function(){try{status('팝업 저장 중...');await putJson('content/popup.json',popupConfig,'CMS: update popup');clean();status('팝업 저장 완료.')}catch(e){status('팝업 저장 실패: '+e.message,false)}};
  const baseSelect=window.selectMedia;window.selectMedia=function(path){if(String(pickerTarget||'').startsWith('popup:')){const k=pickerTarget.slice(6);popupConfig[k]=path;dirty();closeMediaPicker();renderPopupEditor();return}return baseSelect(path)};
  window.loadAll=async function(){await oldLoadAll();try{window.popupConfig=await getJson('content/popup.json')}catch(e){window.popupConfig={...defaults}}norm();renderPopupEditor()};
  window.saveCurrent=async function(){if(currentPage==='popupEditor')return savePopupConfig();return oldSaveCurrent()};
  window.saveAll=async function(){if(window.__popupSaving)return;window.__popupSaving=true;try{await oldSaveAll();await putJson('content/popup.json',popupConfig,'CMS: update popup');clean();status('전체 콘텐츠 저장 완료.')}catch(e){status('전체 저장 실패: '+e.message,false)}finally{window.__popupSaving=false}};
  const sel=document.getElementById('rawFileSelect');if(sel&&![...sel.options].some(o=>o.value==='content/popup.json')){const o=document.createElement('option');o.value='content/popup.json';o.textContent='팝업 데이터 - popup.json';sel.appendChild(o)}
})();