(()=>{
  let staffData={pastorName:'',role:'',quote:'',intro:'',bio:'',vision:[],direction:'',image:''};
  const norm=()=>{if(!staffData||typeof staffData!=='object')staffData={};if(!Array.isArray(staffData.vision))staffData.vision=[];['pastorName','role','quote','intro','bio','direction','image'].forEach(k=>{if(typeof staffData[k]!=='string')staffData[k]=''})};
  const nav=(name,label,after)=>{const n=document.getElementById('sideNav');if(!n||n.querySelector(`[data-page="${name}"]`))return;const b=document.createElement('button');b.dataset.page=name;b.textContent=label;const r=n.querySelector(`[data-page="${after}"]`);r?.nextSibling?n.insertBefore(b,r.nextSibling):n.appendChild(b);b.onclick=()=>open(name,label)};
  const page=(name,html)=>{const ed=document.getElementById('editor');if(!ed||ed.querySelector(`[data-page="${name}"]`))return;const s=document.createElement('section');s.className='page';s.dataset.page=name;s.innerHTML=html;ed.insertBefore(s,ed.querySelector('.savebar')||null)};
  function open(name,label){currentPage=name;document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.dataset.page===name));document.querySelectorAll('#sideNav button').forEach(b=>b.classList.toggle('active',b.dataset.page===name));document.getElementById('pageTitle').textContent=label;document.getElementById('pageDesc').textContent='섬기시는 분들 페이지의 담임목사 소개, 약력, 목회 비전과 사진을 관리합니다.';render()}
  function visionHtml(){return staffData.vision.map((x,i)=>`<article class="cms-item"><div class="cms-item-head"><b>${esc(x.title||'비전')}</b><button class="danger" onclick="deleteStaffVision(${i})">삭제</button></div><div class="item-grid"><div><label>제목</label><input value="${esc(x.title||'')}" oninput="staffData.vision[${i}].title=this.value;dirty()"></div><div class="full"><label>설명</label><input value="${esc(x.text||'')}" oninput="staffData.vision[${i}].text=this.value;dirty()"></div></div></article>`).join('')}
  function render(){norm();const root=document.getElementById('staffEditorRoot');if(!root)return;root.innerHTML=`<section class="card"><div class="section-head"><div><h2>담임목사 소개</h2><p class="muted">홈페이지 ‘섬기시는 분들’ 페이지에 바로 반영됩니다.</p></div><button onclick="saveStaffData()">저장</button></div><div class="form-grid"><div><label>이름</label><input value="${esc(staffData.pastorName)}" oninput="staffData.pastorName=this.value;dirty()"></div><div><label>직책</label><input value="${esc(staffData.role)}" oninput="staffData.role=this.value;dirty()"></div><div class="full"><label>대표 문구</label><textarea oninput="staffData.quote=this.value;dirty()">${esc(staffData.quote)}</textarea></div><div class="full"><label>소개글</label><textarea class="tall" oninput="staffData.intro=this.value;dirty()">${esc(staffData.intro)}</textarea></div><div class="full"><label>목사님 약력</label><textarea class="tall" style="min-height:220px" oninput="staffData.bio=this.value;dirty()">${esc(staffData.bio)}</textarea></div><div class="full"><label>목회 방향</label><textarea oninput="staffData.direction=this.value;dirty()">${esc(staffData.direction)}</textarea></div><div class="full"><label>대표 사진</label><div class="slot-card" style="margin-top:8px"><div class="slot-preview" ${staffData.image?`style="background-image:url('${esc(staffData.image)}?v=${Date.now()}')"`:''}></div><input value="${esc(staffData.image)}" oninput="staffData.image=this.value;dirty()"><div class="slot-actions"><button class="ghost" type="button" onclick="openMediaPicker('staff:image')">기존 이미지</button><button type="button" onclick="quickUploadStaffImage()">새 이미지</button><button class="ghost" type="button" onclick="clearStaffImage()">비우기</button></div></div></div></div></section><section class="card"><div class="section-head"><div><h2>3대 사역 · 목회 비전</h2></div><button onclick="addStaffVision()">＋ 추가</button></div><div id="staffVisionList" class="content-list">${visionHtml()}</div></section>`}
  window.staffData=staffData;
  window.addStaffVision=()=>{staffData.vision.push({title:'새 비전',text:''});render();dirty()};
  window.deleteStaffVision=i=>{staffData.vision.splice(i,1);render();dirty()};
  window.clearStaffImage=()=>{staffData.image='';render();dirty()};
  window.quickUploadStaffImage=()=>{const inp=document.createElement('input');inp.type='file';inp.accept='image/*';inp.onchange=async()=>{const f=inp.files[0];if(!f)return;try{status('이미지 업로드 중...');staffData.image=await uploadBlob(await canvasJpeg(f),f.name);await loadImages();render();dirty();status('사진 적용 완료. 저장을 눌러주세요.')}catch(e){status('업로드 실패: '+e.message,false)}};inp.click()};
  window.saveStaffData=async()=>{try{status('섬기시는 분들 저장 중...');await putJson('content/staff.json',staffData,'CMS: update staff page');clean();status('섬기시는 분들 저장 완료.')}catch(e){status('저장 실패: '+e.message,false)}};
  const oldLoadAll=window.loadAll,oldSaveCurrent=window.saveCurrent,oldSelectMedia=window.selectMedia;
  function install(){
    nav('staffInfo','섬기시는 분들','missionInfo');
    page('staffInfo','<div id="staffEditorRoot"></div>');
    const sel=document.getElementById('rawFileSelect');if(sel&&!Array.from(sel.options).some(o=>o.value==='content/staff.json')){const o=document.createElement('option');o.value='content/staff.json';o.textContent='섬기시는 분들 - staff.json';sel.appendChild(o)}
    window.selectMedia=function(path){if(typeof pickerTarget!=='undefined'&&pickerTarget==='staff:image'){staffData.image=path;render();dirty();closeMediaPicker();return}return oldSelectMedia(path)};
    window.loadAll=async function(){await oldLoadAll();try{staffData=await getJson('content/staff.json');window.staffData=staffData;norm();render()}catch(e){status('섬기시는 분들 로딩 실패: '+e.message,false)}};
    window.saveCurrent=async function(){if(currentPage==='staffInfo')return saveStaffData();return oldSaveCurrent()}
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();
