(()=>{
  const defaults={sectionLabel:'THIS WEEK',sectionTitle:'이번 주 말씀과 주보',bulletinLabel:'BULLETIN',bulletinTitle:'이번 주 교회소식',bulletinText:'예배 안내와 사랑방, 다음세대의 주요 소식을 확인하세요.',bulletinButton:'교회소식 보기 →',bulletinLink:'/news.html'};
  let weekly={...defaults};
  const nav=()=>{const n=document.getElementById('sideNav');if(!n||n.querySelector('[data-page="weeklyHome"]'))return;const b=document.createElement('button');b.dataset.page='weeklyHome';b.textContent='이번 주 말씀·주보';const ref=n.querySelector('[data-page="sermons"]');ref?.nextSibling?n.insertBefore(b,ref.nextSibling):n.appendChild(b);b.onclick=()=>openWeekly()};
  const page=()=>{const ed=document.getElementById('editor');if(!ed||ed.querySelector('[data-page="weeklyHome"]'))return;const s=document.createElement('section');s.className='page';s.dataset.page='weeklyHome';s.innerHTML='<section class="card"><div class="section-head"><div><h2>이번 주 말씀과 주보</h2><p class="muted">홈 화면의 이번 주 말씀 카드와 교회소식 카드를 한 곳에서 편집합니다.</p></div><button onclick="saveWeeklyHome()">이번 주 영역 저장</button></div><div id="weeklyHomeRoot"></div></section>';ed.insertBefore(s,ed.querySelector('.savebar')||null)};
  function openWeekly(){currentPage='weeklyHome';document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.dataset.page==='weeklyHome'));document.querySelectorAll('#sideNav button').forEach(b=>b.classList.toggle('active',b.dataset.page==='weeklyHome'));document.getElementById('pageTitle').textContent='이번 주 말씀·주보';document.getElementById('pageDesc').textContent='홈 화면의 주간 핵심 영역을 편집합니다.';loadWeeklyFromIndex()}
  function latest(){if(!Array.isArray(sermons)||!sermons.length)return null;return [...sermons].sort((a,b)=>String(b.date||'').localeCompare(String(a.date||'')))[0]}
  const set=(k,v)=>{weekly[k]=v;dirty()};
  window.weeklySet=set;
  function render(){const root=document.getElementById('weeklyHomeRoot');if(!root)return;const s=latest()||{};root.innerHTML=`<div class="form-grid"><div><label>섹션 영문 라벨</label><input value="${esc(weekly.sectionLabel)}" oninput="weeklySet('sectionLabel',this.value)"></div><div><label>섹션 제목</label><input value="${esc(weekly.sectionTitle)}" oninput="weeklySet('sectionTitle',this.value)"></div><div class="full"><hr style="border:0;border-top:1px solid var(--line);margin:8px 0 2px"></div><div><label>설교 날짜</label><input id="weeklySermonDate" value="${esc(s.date||'')}"></div><div><label>설교자</label><input id="weeklySermonPreacher" value="${esc((site.latestBulletin&&site.latestBulletin.preacher)||site.pastor||'')}"></div><div class="full"><label>설교 제목</label><input id="weeklySermonTitle" value="${esc(s.title||'')}"></div><div class="full"><label>본문 · 설명</label><textarea id="weeklySermonText">${esc(s.text||'')}</textarea></div><div class="full"><label>설교 영상 URL</label><input id="weeklySermonVideo" value="${esc(s.video||'')}"></div><div class="full"><p class="hint">설교 카드 내용은 설교 목록의 가장 최근 항목과 연동됩니다. 여기서 저장하면 해당 설교 항목도 함께 수정됩니다.</p></div><div class="full"><hr style="border:0;border-top:1px solid var(--line);margin:8px 0 2px"></div><div><label>주보 카드 라벨</label><input value="${esc(weekly.bulletinLabel)}" oninput="weeklySet('bulletinLabel',this.value)"></div><div><label>주보 카드 제목</label><input value="${esc(weekly.bulletinTitle)}" oninput="weeklySet('bulletinTitle',this.value)"></div><div class="full"><label>주보 카드 설명</label><textarea oninput="weeklySet('bulletinText',this.value)">${esc(weekly.bulletinText)}</textarea></div><div><label>버튼 문구</label><input value="${esc(weekly.bulletinButton)}" oninput="weeklySet('bulletinButton',this.value)"></div><div><label>연결 주소</label><input value="${esc(weekly.bulletinLink)}" oninput="weeklySet('bulletinLink',this.value)"></div></div>`}
  async function loadWeeklyFromIndex(){weekly={...defaults};try{const html=await getText('index.html');let m=html.match(/<div class="kicker">([^<]*)<\/div><h2 class="section-title">([^<]*)<\/h2><div class="feature-grid">/);if(m){weekly.sectionLabel=m[1];weekly.sectionTitle=m[2]}m=html.match(/<article class="feature-card"><div class="kicker">([^<]*)<\/div><h3>([^<]*)<\/h3><p>([^<]*)<\/p><a class="text-link" href="([^"]*)">([^<]*)<\/a><\/article>/);if(m){weekly.bulletinLabel=m[1];weekly.bulletinTitle=m[2];weekly.bulletinText=m[3];weekly.bulletinLink=m[4];weekly.bulletinButton=m[5]}}catch(e){console.warn('weekly index parse fallback',e)}render()}
  function escHtmlText(s){return String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}
  async function patchIndex(){let html=await getText('index.html');html=html.replace(/<div class="kicker">[^<]*<\/div><h2 class="section-title">[^<]*<\/h2><div class="feature-grid">/,`<div class="kicker">${escHtmlText(weekly.sectionLabel)}</div><h2 class="section-title">${escHtmlText(weekly.sectionTitle)}</h2><div class="feature-grid">`);html=html.replace(/<article class="feature-card"><div class="kicker">[^<]*<\/div><h3>[^<]*<\/h3><p>[^<]*<\/p><a class="text-link" href="[^"]*">[^<]*<\/a><\/article>/,`<article class="feature-card"><div class="kicker">${escHtmlText(weekly.bulletinLabel)}</div><h3>${escHtmlText(weekly.bulletinTitle)}</h3><p>${escHtmlText(weekly.bulletinText)}</p><a class="text-link" href="${escHtmlText(weekly.bulletinLink)}">${escHtmlText(weekly.bulletinButton)}</a></article>`);await putText('index.html',html,'CMS: update weekly home section')}
  window.saveWeeklyHome=async()=>{try{status('이번 주 말씀·주보 저장 중...');const cur=latest();if(cur){cur.date=document.getElementById('weeklySermonDate').value;cur.title=document.getElementById('weeklySermonTitle').value;cur.text=document.getElementById('weeklySermonText').value;cur.video=document.getElementById('weeklySermonVideo').value}site.latestBulletin=site.latestBulletin||{};site.latestBulletin.date=document.getElementById('weeklySermonDate').value;site.latestBulletin.sermonTitle=document.getElementById('weeklySermonTitle').value;site.latestBulletin.scripture=(document.getElementById('weeklySermonText').value||'').split('·')[0].trim();site.latestBulletin.preacher=document.getElementById('weeklySermonPreacher').value;await saveSite();await saveSermons();await patchIndex();clean();status('이번 주 말씀·주보 저장 완료.')}catch(e){status('저장 실패: '+e.message,false)}};
  function install(){nav();page();const old=window.saveCurrent;window.saveCurrent=async function(){if(currentPage==='weeklyHome')return saveWeeklyHome();return old()}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();