(()=>{
  const path=location.pathname||'/';
  const isHome=path==='/'||path.endsWith('/index.html');
  if(!isHome)return;

  const force=new URLSearchParams(location.search).has('popup');
  if(!force&&sessionStorage.getItem('churchChannelPopupClosed')==='1')return;

  const kakao='https://pf.kakao.com/_BYtgG';
  const youtube='https://youtube.com/channel/UCiGQ15zMavL6wrRaKZzydiQ?si=7lehv1JcI6BnWYHI';
  const style=document.createElement('style');
  style.textContent=`
    .channel-popup-backdrop{position:fixed;inset:0;z-index:5000;background:rgba(10,24,19,.66);backdrop-filter:blur(8px);-webkit-backdrop-filter:blur(8px);display:grid;place-items:center;padding:20px}
    .channel-popup{width:min(920px,100%);max-height:calc(100vh - 36px);overflow:auto;background:linear-gradient(180deg,#fff 0%,#fbfdfc 100%);border-radius:26px;box-shadow:0 32px 100px rgba(0,0,0,.34);position:relative;padding:28px 34px 22px;color:#17231e}
    .channel-popup-close{position:absolute;right:18px;top:18px;width:44px;height:44px;border:1px solid #e7ebe8;border-radius:50%;background:#fff;color:#33453c;font-size:28px;line-height:1;cursor:pointer;box-shadow:0 8px 24px rgba(0,0,0,.08)}
    .channel-popup-top{display:flex;align-items:center;justify-content:space-between;gap:24px;padding-right:60px}.channel-popup-brand{display:flex;align-items:center;gap:13px}.channel-popup-logo{width:54px;height:54px;object-fit:contain}.channel-popup-brand-copy strong{display:block;font-size:20px;color:#16221d;letter-spacing:-.03em}.channel-popup-brand-copy small{display:block;margin-top:2px;font-size:10px;letter-spacing:.09em;color:#66746d}.channel-popup-slogan{text-align:right;color:#98a19c;font-size:13px;line-height:1.5}
    .channel-popup-head{text-align:center;margin:24px auto 22px}.channel-popup h2{font-size:38px;line-height:1.2;letter-spacing:-.05em;margin:0;color:#17231e!important;font-weight:900}.channel-popup h2 b{color:#2f7d58}.channel-popup-sub{margin:10px 0 0;color:#5e6c65;font-size:17px;line-height:1.6}.channel-popup-sub strong{display:block;color:#53655d;font-size:20px;margin-bottom:5px}
    .channel-popup-grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}.channel-box{border-radius:22px;padding:20px;display:grid;grid-template-columns:132px 1fr;gap:18px;align-items:center}.channel-box.kakao{background:linear-gradient(135deg,#fff9dd,#fff4bd);border:1px solid #f2e3a1}.channel-box.youtube{background:linear-gradient(135deg,#fff4f2,#ffe9e6);border:1px solid #f3d3ce}.channel-copy h3{font-size:23px;margin:0 0 7px;color:#151b18}.channel-copy p{font-size:14px;line-height:1.6;color:#6a746f;margin:0 0 14px}.qr-slot{width:132px;aspect-ratio:1;border:2px dashed #c9d1cd;border-radius:16px;background:#fff;display:grid;place-items:center;color:#8b9891;font-size:12px;font-weight:800;overflow:hidden}.kakao .qr-slot{border-color:#e2c537}.youtube .qr-slot{border-color:#e86259}.qr-slot img{width:100%;height:100%;object-fit:cover;display:none}.channel-go{display:flex;align-items:center;justify-content:center;min-height:46px;border-radius:13px;font-weight:900;text-decoration:none;transition:transform .15s ease,box-shadow .15s ease}.channel-go:hover{transform:translateY(-1px)}.kakao .channel-go{background:#f8d51e;color:#171812!important;box-shadow:0 8px 20px rgba(201,164,0,.15)}.youtube .channel-go{background:#ff3131;color:#fff!important;box-shadow:0 8px 20px rgba(220,0,0,.15)}
    .channel-popup-signature{text-align:center;padding:22px 10px 6px;color:#4f7968;font-size:16px;letter-spacing:.02em}.channel-popup-signature small{display:block;margin-top:5px;color:#a2aaa6;letter-spacing:.18em;font-size:10px}.channel-popup-foot{display:flex;align-items:center;justify-content:space-between;gap:14px;margin-top:10px;padding-top:14px;border-top:1px solid #edf0ee;font-size:13px;color:#707d76}.channel-popup-foot button{border:1px solid #e0e5e2;background:#fff;color:#53645b;font-weight:800;cursor:pointer;padding:9px 13px;border-radius:10px}
    @media(max-width:720px){.channel-popup-backdrop{padding:10px}.channel-popup{padding:20px 16px 16px;border-radius:20px}.channel-popup-top{padding-right:48px}.channel-popup-slogan{display:none}.channel-popup-logo{width:44px;height:44px}.channel-popup-brand-copy strong{font-size:17px}.channel-popup-head{margin:20px 0 18px}.channel-popup h2{font-size:28px}.channel-popup-sub{font-size:14px}.channel-popup-sub strong{font-size:16px}.channel-popup-grid{grid-template-columns:1fr}.channel-box{grid-template-columns:96px 1fr;padding:14px;gap:13px}.qr-slot{width:96px}.channel-copy h3{font-size:19px}.channel-copy p{font-size:12px;margin-bottom:10px}.channel-go{min-height:40px;font-size:13px}.channel-popup-signature{font-size:13px;padding-top:15px}.channel-popup-foot{font-size:12px}.channel-popup-close{width:40px;height:40px;font-size:24px}}
  `;
  document.head.appendChild(style);

  const wrap=document.createElement('div');
  wrap.className='channel-popup-backdrop';
  wrap.setAttribute('role','dialog');wrap.setAttribute('aria-modal','true');wrap.setAttribute('aria-label','모현소망교회 채널 안내');
  wrap.innerHTML=`<section class="channel-popup"><button class="channel-popup-close" type="button" aria-label="팝업 닫기">×</button><div class="channel-popup-top"><div class="channel-popup-brand"><img class="channel-popup-logo" src="/assets/site/logo.png" alt="모현소망교회 로고"><span class="channel-popup-brand-copy"><strong>모현소망교회</strong><small>MOHYEON SOMANG CHURCH</small></span></div><div class="channel-popup-slogan">성령과 진리로 예배드리는 교회<br>요한복음 4:24</div></div><div class="channel-popup-head"><h2>모현소망교회 <b>소식 알아보기 !</b></h2><p class="channel-popup-sub"><strong>&lt; 카카오톡 채널 &amp; 유튜브 &gt;</strong>교회 소식과 말씀 영상을 더 편하게 만나보세요.</p></div><div class="channel-popup-grid"><article class="channel-box kakao"><div class="qr-slot" data-qr="kakao"><img alt="카카오톡 채널 QR"><span>카카오톡<br>QR 이미지 영역</span></div><div class="channel-copy"><h3>카카오톡 채널</h3><p>교회 공지와 행사, 새로운 소식을 가장 빠르게 받아보세요.</p><a class="channel-go" href="${kakao}" target="_blank" rel="noopener">카카오톡 채널 바로가기 ›</a></div></article><article class="channel-box youtube"><div class="qr-slot" data-qr="youtube"><img alt="YouTube 채널 QR"><span>YouTube<br>QR 이미지 영역</span></div><div class="channel-copy"><h3>YouTube 채널</h3><p>주일예배 말씀과 교회 영상을 편리하게 확인하세요.</p><a class="channel-go" href="${youtube}" target="_blank" rel="noopener">YouTube 채널 바로가기 ›</a></div></article></div><div class="channel-popup-signature">함께 걸어가는 믿음의 길, 모현소망교회<small>MOHYEON SOMANG CHURCH</small></div><div class="channel-popup-foot"><span>QR 이미지는 등록 후 이 자리에 표시됩니다.</span><button type="button" data-close-today>이번 접속에서 닫기</button></div></section>`;
  document.body.appendChild(wrap);

  const close=()=>wrap.remove();
  wrap.querySelector('.channel-popup-close').onclick=close;
  wrap.querySelector('[data-close-today]').onclick=()=>{sessionStorage.setItem('churchChannelPopupClosed','1');close()};
  wrap.addEventListener('click',e=>{if(e.target===wrap)close()});
  document.addEventListener('keydown',e=>{if(e.key==='Escape'&&document.body.contains(wrap))close()});
})();
