(()=>{
  const path=location.pathname||'/';
  const isHome=path==='/'||path.endsWith('/index.html');
  if(!isHome)return;
  const force=new URLSearchParams(location.search).has('popup');
  if(!force&&sessionStorage.getItem('churchChannelPopupClosed')==='1')return;
  const kakao='https://pf.kakao.com/_BYtgG';
  const youtube='https://youtube.com/channel/UCiGQ15zMavL6wrRaKZzydiQ?si=7lehv1JcI6BnWYHI';
  const style=document.createElement('style');
  style.textContent=`
  .channel-popup-backdrop{position:fixed;inset:0;z-index:5000;background:rgba(10,24,19,.68);backdrop-filter:blur(8px);-webkit-backdrop-filter:blur(8px);display:grid;place-items:center;padding:20px}
  .channel-popup{width:min(920px,100%);max-height:calc(100vh - 36px);overflow:auto;background:linear-gradient(155deg,#183229,#10251e);border:1px solid rgba(255,255,255,.12);border-radius:26px;box-shadow:0 32px 100px rgba(0,0,0,.42);position:relative;padding:28px 34px 22px;color:#fff}
  .channel-popup-close{position:absolute;right:18px;top:18px;width:44px;height:44px;border:1px solid rgba(255,255,255,.75);border-radius:50%;background:#fff;color:#263c33;font-size:28px;line-height:1;cursor:pointer;box-shadow:0 8px 24px rgba(0,0,0,.18)}
  .channel-popup-top{display:flex;justify-content:flex-end;align-items:flex-start;min-height:58px;padding-right:62px}.channel-popup-slogan{text-align:right;color:#e2eae6;font-size:13px;line-height:1.5}
  .channel-popup-head{text-align:center;margin:8px auto 22px}.channel-popup h2{font-size:38px;line-height:1.2;letter-spacing:-.05em;margin:0;color:#fff!important;font-weight:900;text-shadow:0 2px 16px rgba(0,0,0,.16)}.channel-popup h2 b{color:#58d28e}.channel-popup-sub{margin:10px 0 0;color:#eef5f1;font-size:17px;line-height:1.6}.channel-popup-sub strong{display:block;color:#fff;font-size:20px;margin-bottom:5px}
  .channel-popup-grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}.channel-box{border-radius:22px;padding:20px;display:grid;grid-template-columns:132px 1fr;gap:18px;align-items:center;color:#17231e}.channel-box.kakao{background:linear-gradient(135deg,#fff9dd,#fff4bd);border:1px solid #f2e3a1}.channel-box.youtube{background:linear-gradient(135deg,#fff4f2,#ffe9e6);border:1px solid #f3d3ce}.channel-copy h3{font-size:23px;margin:0 0 7px;color:#151b18}.channel-copy p{font-size:14px;line-height:1.6;color:#5e6963;margin:0 0 14px}.qr-slot{width:132px;aspect-ratio:1;border:2px dashed #c9d1cd;border-radius:16px;background:#fff;display:grid;place-items:center;color:#7d8a83;font-size:12px;font-weight:800;overflow:hidden}.kakao .qr-slot{border-color:#e2c537}.youtube .qr-slot{border-color:#e86259}.channel-go{display:flex;align-items:center;justify-content:center;min-height:46px;border-radius:13px;font-weight:900;text-decoration:none}.kakao .channel-go{background:#f8d51e;color:#171812!important}.youtube .channel-go{background:#ff3131;color:#fff!important}
  .channel-popup-signature{text-align:center;padding:22px 10px 6px;color:#d8eee3;font-size:16px}.channel-popup-signature small{display:block;margin-top:5px;color:#aebdb6;letter-spacing:.18em;font-size:10px}.channel-popup-foot{display:flex;align-items:center;justify-content:space-between;gap:14px;margin-top:10px;padding-top:14px;border-top:1px solid rgba(255,255,255,.13);font-size:13px;color:#c6d2cc}.channel-popup-foot button{border:1px solid rgba(255,255,255,.22);background:rgba(255,255,255,.09);color:#fff;font-weight:800;cursor:pointer;padding:9px 13px;border-radius:10px}
  @media(max-width:720px){.channel-popup-backdrop{padding:10px}.channel-popup{padding:20px 16px 16px;border-radius:20px}.channel-popup-top{padding-right:48px;min-height:44px}.channel-popup-slogan{display:none}.channel-popup-head{margin:4px 0 18px}.channel-popup h2{font-size:28px}.channel-popup-sub{font-size:14px}.channel-popup-sub strong{font-size:16px}.channel-popup-grid{grid-template-columns:1fr}.channel-box{grid-template-columns:96px 1fr;padding:14px;gap:13px}.qr-slot{width:96px}.channel-copy h3{font-size:19px}.channel-copy p{font-size:12px;margin-bottom:10px}.channel-go{min-height:40px;font-size:13px}.channel-popup-signature{font-size:13px;padding-top:15px}.channel-popup-foot{font-size:12px}.channel-popup-close{width:40px;height:40px;font-size:24px}}
  `;
  document.head.appendChild(style);
  const wrap=document.createElement('div');
  wrap.className='channel-popup-backdrop';
  wrap.setAttribute('role','dialog');wrap.setAttribute('aria-modal','true');wrap.setAttribute('aria-label','모현소망교회 채널 안내');
  wrap.innerHTML=`<section class="channel-popup"><button class="channel-popup-close" type="button" aria-label="팝업 닫기">×</button><div class="channel-popup-top"><div class="channel-popup-slogan">성령과 진리로 예배드리는 교회<br>요한복음 4:24</div></div><div class="channel-popup-head"><h2>모현소망교회 <b>소식 알아보기 !</b></h2><p class="channel-popup-sub"><strong>&lt; 카카오톡 채널 &amp; 유튜브 &gt;</strong>교회 소식과 말씀 영상을 더 편하게 만나보세요.</p></div><div class="channel-popup-grid"><article class="channel-box kakao"><div class="qr-slot"><span>카카오톡<br>QR 이미지 영역</span></div><div class="channel-copy"><h3>카카오톡 채널</h3><p>교회 공지와 행사, 새로운 소식을 가장 빠르게 받아보세요.</p><a class="channel-go" href="${kakao}" target="_blank" rel="noopener">카카오톡 채널 바로가기 ›</a></div></article><article class="channel-box youtube"><div class="qr-slot"><span>YouTube<br>QR 이미지 영역</span></div><div class="channel-copy"><h3>YouTube 채널</h3><p>주일예배 말씀과 교회 영상을 편리하게 확인하세요.</p><a class="channel-go" href="${youtube}" target="_blank" rel="noopener">YouTube 채널 바로가기 ›</a></div></article></div><div class="channel-popup-signature">함께 걸어가는 믿음의 길, 모현소망교회<small>MOHYEON SOMANG CHURCH</small></div><div class="channel-popup-foot"><span>QR 이미지는 등록 후 이 자리에 표시됩니다.</span><button type="button" data-close-today>이번 접속에서 닫기</button></div></section>`;
  document.body.appendChild(wrap);
  const close=()=>wrap.remove();
  wrap.querySelector('.channel-popup-close').onclick=close;
  wrap.querySelector('[data-close-today]').onclick=()=>{sessionStorage.setItem('churchChannelPopupClosed','1');close()};
  wrap.addEventListener('click',e=>{if(e.target===wrap)close()});
  document.addEventListener('keydown',e=>{if(e.key==='Escape'&&document.body.contains(wrap))close()});
})();