(()=>{
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const path=location.pathname||'/';
  function style(){if(document.getElementById('churchInfoStyle'))return;const s=document.createElement('style');s.id='churchInfoStyle';s.textContent=`
    .church-info-section{padding:64px 0}.church-info-section.soft{background:linear-gradient(180deg,#f6faf7,#fff)}
    .notice-grid,.mission-grid,.support-grid{display:grid;gap:16px}.notice-grid{grid-template-columns:repeat(3,1fr)}.mission-grid{grid-template-columns:repeat(5,1fr)}.support-grid{grid-template-columns:repeat(2,1fr)}
    .info-card{border:1px solid var(--line,#e4e8e4);border-radius:22px;background:#fff;padding:22px;box-shadow:0 10px 26px rgba(20,54,41,.05)}
    .info-card .num{width:34px;height:34px;border-radius:999px;display:grid;place-items:center;background:#edf5f0;color:var(--green,#2f6b4f);font-weight:900;margin-bottom:14px}
    .info-card h3{margin:0 0 8px;font-size:20px}.info-card p{margin:0;color:var(--muted,#6b756f);line-height:1.7}
    .support-list{display:grid;gap:10px;margin-top:20px}.support-item{display:flex;gap:10px;align-items:flex-start;padding:13px 15px;border-radius:14px;background:#f7faf8}.support-item:before{content:'•';color:var(--green,#2f6b4f);font-weight:900}
    .transport-card{display:grid;grid-template-columns:1fr auto;gap:18px;align-items:center;border:1px solid var(--line,#e4e8e4);border-radius:24px;background:#fff;padding:26px}.transport-card h2{margin:0 0 8px}.transport-card p{margin:0 0 6px;color:var(--muted,#6b756f)}.transport-card a{display:inline-flex;padding:12px 18px;border-radius:999px;background:var(--green,#2f6b4f);color:#fff;font-weight:800}
    @media(max-width:900px){.notice-grid,.mission-grid,.support-grid{grid-template-columns:1fr}.church-info-section{padding:46px 0}.transport-card{grid-template-columns:1fr}.transport-card a{justify-content:center}}
  `;document.head.appendChild(s)}
  function afterThisWeek(node){const sections=[...document.querySelectorAll('main>section')];const target=sections.find(x=>x.querySelector('.section-title')?.textContent.includes('이번 주 말씀과 주보'));if(target)target.insertAdjacentElement('afterend',node);else document.querySelector('main')?.appendChild(node)}
  function renderHome(d){if(document.getElementById('homeCoreNotices'))return;const list=Array.isArray(d.homeNotices)?d.homeNotices:[];if(!list.length)return;const sec=document.createElement('section');sec.id='homeCoreNotices';sec.className='church-info-section soft';sec.innerHTML=`<div class="container"><div class="kicker">THIS WEEK NOTICE</div><h2 class="section-title">이번 주 핵심 공지</h2><div class="notice-grid">${list.map((x,i)=>`<article class="info-card"><div class="num">${i+1}</div><h3>${esc(x.title)}</h3><p>${esc(x.text)}</p></article>`).join('')}</div></div>`;afterThisWeek(sec)}
  function renderAbout(d){const main=document.querySelector('main');if(!main)return;if(!document.getElementById('missionStatement')){const sec=document.createElement('section');sec.id='missionStatement';sec.className='church-info-section soft';const items=Array.isArray(d.missionStatement)?d.missionStatement:[];sec.innerHTML=`<div class="container"><div class="kicker">MISSION</div><h2 class="section-title">모현소망교회 사명선언문</h2><div class="mission-grid">${items.map((x,i)=>`<article class="info-card"><div class="num">${i+1}</div><h3>${esc(x.title)}</h3><p>${esc(x.text)}</p></article>`).join('')}</div></div>`;main.appendChild(sec)}if(!document.getElementById('supportMinistry')){const sec=document.createElement('section');sec.id='supportMinistry';sec.className='church-info-section';const items=Array.isArray(d.supportItems)?d.supportItems:[];sec.innerHTML=`<div class="container"><div class="kicker">MISSION & SUPPORT</div><h2 class="section-title">선교와 후원</h2><p class="section-lead">${esc(d.supportIntro||'')}</p><div class="support-list">${items.map(x=>`<div class="support-item">${esc(x)}</div>`).join('')}</div></div>`;main.appendChild(sec)}}
  function renderVisit(d){if(document.getElementById('transportInfo'))return;const t=d.transport||{};if(!t.title&&!t.text)return;const main=document.querySelector('main');if(!main)return;const sec=document.createElement('section');sec.id='transportInfo';sec.className='church-info-section soft';const tel=String(t.phone||'').replace(/[^0-9+]/g,'');sec.innerHTML=`<div class="container"><div class="transport-card"><div><div class="kicker">CHURCH SHUTTLE</div><h2>${esc(t.title||'차량 운행 안내')}</h2><p>${esc(t.text||'')}</p><p><b>${esc(t.contact||'')}</b></p></div>${tel?`<a href="tel:${tel}">전화로 신청</a>`:''}</div></div>`;main.appendChild(sec)}
  async function run(){style();try{const r=await fetch('/content/church-info.json?v='+Date.now(),{cache:'no-store'});const d=await r.json();if(path==='/'||path.endsWith('/index.html'))renderHome(d);if(path.endsWith('/about.html'))renderAbout(d);if(path.endsWith('/visit.html'))renderVisit(d)}catch(e){console.warn('church info load failed',e)}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run,{once:true});else run();
})();
